name: Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker images
        run: docker build . --tag licensee

      - name: Smoke test
        run: docker run licensee